<?php

namespace App\Filament\Resources\Operations\ImplementationProjectResource\Pages;

use App\Filament\Resources\Operations\ImplementationProjectResource;
use Filament\Actions;
use Filament\Resources\Pages\ListRecords;

class ListImplementationProjects extends ListRecords
{
    protected static string $resource = ImplementationProjectResource::class;

    protected function getHeaderActions(): array
    {
        return [
            // We usually wouldn't create an implementation project manually here (they are generated by services),
            // but we'll leave the action for testing purposes.
            Actions\CreateAction::make(),
        ];
    }
}
