@php
    $isLatest = $isLatest ?? false;
    $version = $media->getCustomProperty('version', $record->version ?? 1);
    $byName = $media->getCustomProperty('generated_by_name', 'System');
    $date = $media->created_at ? $media->created_at->format('M d, Y h:i A') : '';
    $size = $media->human_readable_size ?? '';
    
    $icon = $isLatest ? 'heroicon-m-document-check' : 'heroicon-m-document-text';
    $iconColor = $isLatest ? 'text-primary-500 dark:text-primary-400' : 'text-gray-400 dark:text-gray-500';
    $label = "Quotation Document v{$version}";
    $modalTitle = "Official Client Quotation PDF (v{$version}) - {$record->quote_number}";
    $streamUrl = route('billing.quotation.pdf', ['quote' => $record->id, 'media_id' => $media->id]);
    $downloadUrl = route('billing.quotation.pdf.download', ['quote' => $record->id, 'media_id' => $media->id]);
@endphp

<li style="display: flex; align-items: center; justify-content: space-between; padding: 0.75rem; border-radius: 0.5rem; {{ $isLatest ? 'background: rgba(37, 99, 235, 0.05); border: 1px solid rgba(37, 99, 235, 0.25);' : 'background: rgba(128, 128, 128, 0.04); border: 1px solid rgba(128, 128, 128, 0.15);' }}">
    <div style="display: flex; align-items: center; gap: 0.75rem; min-width: 0;">
        <x-filament::icon :icon="$icon" style="width: 1.25rem; height: 1.25rem; {{ $isLatest ? 'color: #2563eb;' : 'color: #9ca3af;' }} flex-shrink: 0;" />
        <div style="display: flex; flex-direction: column; min-width: 0;">
            <div style="display: flex; align-items: center; gap: 0.5rem;">
                <a href="#" 
                   wire:click.prevent="mountAction('viewHistoryPdf', { mediaId: {{ $media->id }}, title: '{{ addslashes($modalTitle) }}' })" 
                   style="font-size: 0.875rem; font-weight: 600; color: #2563eb; text-decoration: none; overflow: hidden; text-overflow: ellipsis; white-space: nowrap;">
                   {{ $label }}
                </a>
                @if($isLatest)
                    <span style="display: inline-flex; align-items: center; padding: 0.125rem 0.375rem; border-radius: 0.25rem; font-size: 0.625rem; font-weight: 700; background: rgba(16, 185, 129, 0.15); color: #047857; border: 1px solid rgba(16, 185, 129, 0.3);">
                        Current
                    </span>
                @endif
            </div>
            <div style="font-size: 0.75rem; color: #6b7280; display: flex; align-items: center; gap: 0.5rem; margin-top: 0.125rem;">
                <span>{{ $media->file_name }}</span>
                <span>•</span>
                <span>Generated by {{ $byName }}</span>
                @if($size)
                    <span>•</span>
                    <span>{{ $size }}</span>
                @endif
            </div>
        </div>
    </div>
    
    <div style="display: flex; align-items: center; gap: 0.75rem; flex-shrink: 0; margin-left: 1rem;">
        <span style="font-size: 0.75rem; color: #6b7280;">{{ $date }}</span>
        <div style="display: flex; align-items: center; gap: 0.25rem;">
            <a href="#"
               wire:click.prevent="mountAction('viewHistoryPdf', { mediaId: {{ $media->id }}, title: '{{ addslashes($modalTitle) }}' })"
               title="View in Modal"
               style="padding: 0.25rem; color: #6b7280; text-decoration: none;">
                <x-filament::icon icon="heroicon-m-eye" style="width: 1rem; height: 1rem;" />
            </a>
            <a href="{{ $streamUrl }}"
               target="_blank"
               title="Open in new tab"
               style="padding: 0.25rem; color: #6b7280; text-decoration: none;">
                <x-filament::icon icon="heroicon-m-arrow-top-right-on-square" style="width: 1rem; height: 1rem;" />
            </a>
            <a href="{{ $downloadUrl }}"
               download
               title="Download PDF"
               style="padding: 0.25rem; color: #6b7280; text-decoration: none;">
                <x-filament::icon icon="heroicon-m-arrow-down-tray" style="width: 1rem; height: 1rem;" />
            </a>
        </div>
    </div>
</li>
