@php
    $isLatest = $isLatest ?? false;
    $version = $media->getCustomProperty('version', $record->version ?? 1);
    $byName = $media->getCustomProperty('generated_by_name', 'System');
    $date = $media->created_at ? $media->created_at->format('M d, Y h:i A') : '';
    $size = $media->human_readable_size ?? '';
    
    $icon = $isLatest ? 'heroicon-m-document-check' : 'heroicon-m-document-text';
    $iconColor = $isLatest ? 'text-primary-500 dark:text-primary-400' : 'text-gray-400 dark:text-gray-500';
    $label = "Quotation Document v{$version}";
    $modalTitle = "Official Client Quotation PDF (v{$version}) - {$record->quote_number}";
    $streamUrl = route('billing.quotation.pdf', ['quote' => $record->id, 'media_id' => $media->id]);
    $downloadUrl = route('billing.quotation.pdf.download', ['quote' => $record->id, 'media_id' => $media->id]);
@endphp

<li class="flex items-center justify-between p-3 rounded-lg {{ $isLatest ? 'bg-primary-50/50 dark:bg-primary-950/20 border border-primary-200/70 dark:border-primary-800/50' : 'bg-gray-50 dark:bg-white/5 border border-gray-200 dark:border-white/10' }}">
    <div class="flex items-center gap-3 min-w-0">
        <x-filament::icon :icon="$icon" class="w-5 h-5 {{ $iconColor }} shrink-0" />
        <div class="flex flex-col min-w-0">
            <div class="flex items-center gap-2">
                <a href="#" 
                   wire:click.prevent="mountAction('viewHistoryPdf', { mediaId: {{ $media->id }}, title: '{{ addslashes($modalTitle) }}' })" 
                   class="text-sm font-semibold text-primary-600 hover:text-primary-500 hover:underline dark:text-primary-400 dark:hover:text-primary-300 truncate">
                   {{ $label }}
                </a>
                @if($isLatest)
                    <span class="inline-flex items-center px-1.5 py-0.5 rounded text-[10px] font-bold bg-success-100 text-success-700 dark:bg-success-950/40 dark:text-success-400 border border-success-200 dark:border-success-800">
                        Current
                    </span>
                @endif
            </div>
            <div class="text-xs text-gray-500 dark:text-gray-400 flex items-center gap-2 mt-0.5">
                <span>{{ $media->file_name }}</span>
                <span>•</span>
                <span>Generated by {{ $byName }}</span>
                @if($size)
                    <span>•</span>
                    <span>{{ $size }}</span>
                @endif
            </div>
        </div>
    </div>
    
    <div class="flex items-center gap-3 shrink-0 ml-4">
        <span class="text-xs text-gray-500 dark:text-gray-400 hidden sm:inline">{{ $date }}</span>
        <div class="flex items-center gap-1">
            <a href="#"
               wire:click.prevent="mountAction('viewHistoryPdf', { mediaId: {{ $media->id }}, title: '{{ addslashes($modalTitle) }}' })"
               title="View in Modal"
               class="p-1 text-gray-500 hover:text-primary-600 dark:text-gray-400 dark:hover:text-primary-400 transition-colors">
                <x-filament::icon icon="heroicon-m-eye" class="w-4 h-4" />
            </a>
            <a href="{{ $streamUrl }}"
               target="_blank"
               title="Open in new tab"
               class="p-1 text-gray-500 hover:text-primary-600 dark:text-gray-400 dark:hover:text-primary-400 transition-colors">
                <x-filament::icon icon="heroicon-m-arrow-top-right-on-square" class="w-4 h-4" />
            </a>
            <a href="{{ $downloadUrl }}"
               download
               title="Download PDF"
               class="p-1 text-gray-500 hover:text-primary-600 dark:text-gray-400 dark:hover:text-primary-400 transition-colors">
                <x-filament::icon icon="heroicon-m-arrow-down-tray" class="w-4 h-4" />
            </a>
        </div>
    </div>
</li>
