<?php

namespace Tek2991\Accounting\Database\Seeders;

use Illuminate\Database\Seeder;
use Faker\Factory as Faker;
use Carbon\Carbon;
use Tek2991\Accounting\Enums\ContactType;
use Tek2991\Accounting\Enums\DocumentLineType;
use Tek2991\Accounting\Models\BankAccount;
use Tek2991\Accounting\Models\Contact;
use Tek2991\Accounting\Models\Item;
use Tek2991\Accounting\Models\State;
use Tek2991\Accounting\Models\Tax;
use Tek2991\Accounting\Services\InvoiceService;
use Tek2991\Accounting\Services\BillService;
use App\Models\Branch;

class DemoTransactionsSeeder extends Seeder
{
    public function run(): void
    {
        $faker = Faker::create('en_IN');
        $invoiceService = app(InvoiceService::class);
        $billService = app(BillService::class);
        $branchContext = app(\Tek2991\Accounting\Services\BranchContext::class);

        $branches = Branch::whereIn('code', ['GHY', 'BLR'])->get();
        $bankAccounts = BankAccount::all();
        
        $contacts = Contact::all();
        $customers = $contacts->filter(fn($c) => in_array($c->type, [ContactType::Customer, ContactType::Both]))->values();
        $vendors = $contacts->filter(fn($c) => in_array($c->type, [ContactType::Vendor, ContactType::Both]))->values();
        
        $items = Item::all();
        $gst18 = Tax::where('name', 'GST 18%')->first();
        
        $assam = State::where('name', 'Assam')->first();
        $maharashtra = State::where('name', 'Maharashtra')->first();
        $delhi = State::where('name', 'Delhi')->first();
        $statesForSupply = collect([$assam, $assam, $assam, $maharashtra, $delhi])->filter()->values();

        $startMonth = \Tek2991\Accounting\Facades\Accounting::getFiscalYearStart();
        $currentYear = now()->year;
        $startYear = now()->month >= $startMonth ? $currentYear : $currentYear - 1;
        $startDate = Carbon::create($startYear, $startMonth, 1)->startOfDay();
        
        $maxDaysDiff = max(1, $startDate->diffInDays(now()));

        foreach ($branches as $currentBranch) {
            $branchContext->set($currentBranch);
            
            for ($i = 0; $i < 5; $i++) {
                $date = now()->subDays(rand(0, $maxDaysDiff - 1));
                
                // INVOICES
                if ($customers->isNotEmpty() && $items->isNotEmpty() && $gst18) {
                    $customer = $faker->randomElement($customers);
                    $invoice = $invoiceService->create($currentBranch, [
                        'contact_id' => $customer->id,
                        'issue_date' => $date->format('Y-m-d'),
                        'due_date' => $date->copy()->addDays(30)->format('Y-m-d'),
                        'place_of_supply_state_id' => $statesForSupply->isNotEmpty() ? $faker->randomElement($statesForSupply)->id : null,
                        'notes' => 'Generated by Comprehensive Demo Seeder',
                    ]);

                    $numItems = rand(1, 4);
                    for ($j = 0; $j < $numItems; $j++) {
                        $item = $faker->randomElement($items);
                        $invoice->items()->create([
                            'line_type' => DocumentLineType::Item,
                            'item_id' => $item->id,
                            'description' => $item->name,
                            'quantity' => rand(1, 10),
                            'unit_price' => $item->sale_price,
                            'tax_id' => $gst18->id,
                        ]);
                    }

                    $invoiceService->recalculateTotals($invoice);
                    $invoiceService->post($invoice);

                    // 75% chance of payment
                    if (rand(1, 100) <= 75 && $bankAccounts->isNotEmpty()) {
                        $paymentDate = $date->copy()->addDays(rand(1, 30));
                        if ($paymentDate->isPast()) {
                            $invoiceService->recordPayment($invoice, [
                                'payment_account_id' => $faker->randomElement($bankAccounts)->account_id,
                                'payment_date' => $paymentDate->format('Y-m-d'),
                                'amount' => $invoice->grand_total,
                                'reference' => 'PAY-' . $faker->bothify('####????'),
                            ]);
                        }
                    }
                }

                // BILLS
                if ($vendors->isNotEmpty() && $items->isNotEmpty() && $gst18) {
                    $vendor = $faker->randomElement($vendors);
                    $bill = $billService->create($currentBranch, [
                        'contact_id' => $vendor->id,
                        'issue_date' => $date->format('Y-m-d'),
                        'due_date' => $date->copy()->addDays(30)->format('Y-m-d'),
                        'place_of_supply_state_id' => $statesForSupply->isNotEmpty() ? $faker->randomElement($statesForSupply)->id : null,
                        'notes' => 'Generated by Comprehensive Demo Seeder',
                    ]);

                    $numItems = rand(1, 4);
                    for ($j = 0; $j < $numItems; $j++) {
                        $item = $faker->randomElement($items);
                        $bill->items()->create([
                            'line_type' => DocumentLineType::Item,
                            'item_id' => $item->id,
                            'description' => $item->name,
                            'quantity' => rand(1, 5),
                            'unit_price' => $item->purchase_price,
                            'tax_id' => $gst18->id,
                        ]);
                    }

                    $billService->recalculateTotals($bill);
                    $billService->post($bill);

                    // 80% chance of payment
                    if (rand(1, 100) <= 80 && $bankAccounts->isNotEmpty()) {
                        $paymentDate = $date->copy()->addDays(rand(1, 30));
                        if ($paymentDate->isPast()) {
                            $billService->recordPayment($bill, [
                                'payment_account_id' => $faker->randomElement($bankAccounts)->account_id,
                                'payment_date' => $paymentDate->format('Y-m-d'),
                                'amount' => $bill->grand_total,
                                'reference' => 'BILL-PAY-' . $faker->bothify('####????'),
                            ]);
                        }
                    }
                }
            }
        }
    }
}
