@php
    $mediaItems = collect();
    
    if ($record) {
        $generated = $record->getMedia('generated_quote_pdf');
        $legacy = $record->getMedia('quote_pdf');
        $mediaItems = $generated->concat($legacy)->sortByDesc('created_at')->values();
    }
    $mediaCount = $mediaItems->count();
@endphp

<div class="w-full">
    @if($mediaItems->isEmpty())
        <div class="p-5 rounded-lg bg-amber-50 dark:bg-amber-950/20 border border-amber-200 dark:border-amber-800/40 text-sm text-amber-800 dark:text-amber-300 flex items-center gap-3">
            <x-filament::icon icon="heroicon-o-document-text" class="w-6 h-6 text-amber-600 dark:text-amber-400 shrink-0" />
            <div>
                <div class="font-bold text-sm">Official Quotation PDF Not Generated Yet</div>
                <div class="text-xs text-amber-700 dark:text-amber-400 mt-0.5">Click <strong>"Generate Quotation"</strong> above to compile the official customer-facing PDF with current line items and tax components.</div>
            </div>
        </div>
    @else
        <div class="border border-gray-200 dark:border-white/10 rounded-lg overflow-hidden bg-white dark:bg-gray-900 shadow-sm">
            <div class="px-4 py-3 bg-gray-50/80 dark:bg-white/5 border-b border-gray-200 dark:border-white/10 flex flex-wrap items-center justify-between gap-3">
                <div class="flex items-center gap-2">
                    <x-filament::icon icon="heroicon-m-document-duplicate" class="w-4 h-4 text-primary-500" />
                    <span class="font-bold text-xs text-gray-900 dark:text-white uppercase tracking-wider">Generated Quotation Documents</span>
                    <span class="inline-flex items-center px-2 py-0.5 rounded-full text-[11px] font-semibold bg-primary-100 dark:bg-primary-950/50 text-primary-700 dark:text-primary-300 border border-primary-200 dark:border-primary-800/60">
                        {{ $mediaCount }} {{ $mediaCount === 1 ? 'version' : 'versions' }}
                    </span>
                </div>
                <div class="text-xs text-gray-500 dark:text-gray-400">
                    Quotation Grand Total: <strong class="text-gray-900 dark:text-white font-bold text-sm">₹{{ number_format($record->total_amount, 2) }}</strong>
                </div>
            </div>

            <div class="overflow-x-auto">
                <table class="w-full text-left text-xs">
                    <thead>
                        <tr class="bg-gray-50/50 dark:bg-white/[0.02] border-b border-gray-200 dark:border-white/10 text-gray-500 dark:text-gray-400 font-semibold uppercase tracking-wider text-[11px]">
                            <th class="px-4 py-3 w-[15%]">Version</th>
                            <th class="px-4 py-3 w-[30%]">File Name</th>
                            <th class="px-4 py-3 w-[20%]">Generated On</th>
                            <th class="px-4 py-3 w-[15%]">Generated By</th>
                            <th class="px-4 py-3 w-[8%]">Size</th>
                            <th class="px-4 py-3 w-[12%] text-right">Actions</th>
                        </tr>
                    </thead>
                    <tbody class="divide-y divide-gray-200 dark:divide-white/10">
                        @foreach ($mediaItems as $index => $media)
                            @php
                                $isLatest = ($index === 0);
                                $ver = $media->getCustomProperty('version') ?? ($mediaCount - $index);
                                $dateStr = $media->created_at ? $media->created_at->format('M d, Y h:i A') : '—';
                                $byName = $media->getCustomProperty('generated_by_name') ?? 'System';
                                $sizeStr = $media->human_readable_size ?? '—';
                                $modalTitle = "Official Client Quotation PDF (v{$ver}) - {$record->quote_number}";
                                $streamUrl = route('billing.quotation.pdf', ['quote' => $record->id, 'media_id' => $media->id]);
                                $downloadUrl = route('billing.quotation.pdf.download', ['quote' => $record->id, 'media_id' => $media->id]);
                            @endphp
                            <tr class="{{ $isLatest ? 'bg-primary-50/30 dark:bg-primary-950/10 hover:bg-primary-50/50 dark:hover:bg-primary-950/20' : 'hover:bg-gray-50/60 dark:hover:bg-white/[0.02]' }} transition-colors">
                                <td class="px-4 py-3">
                                    @if($isLatest)
                                        <span class="inline-flex items-center gap-1.5 px-2 py-0.5 rounded text-[11px] font-bold bg-success-100 text-success-700 dark:bg-success-950/50 dark:text-success-400 border border-success-200 dark:border-success-800">
                                            <span class="w-1.5 h-1.5 rounded-full bg-success-500"></span>
                                            v{{ $ver }} (Latest)
                                        </span>
                                    @else
                                        <span class="inline-flex items-center px-2 py-0.5 rounded text-[11px] font-semibold bg-gray-100 text-gray-600 dark:bg-white/5 dark:text-gray-400 border border-gray-200 dark:border-white/10">
                                            v{{ $ver }} (Archive)
                                        </span>
                                    @endif
                                </td>
                                <td class="px-4 py-3 font-medium text-gray-900 dark:text-white">
                                    <div class="flex items-center gap-2">
                                        <x-filament::icon icon="heroicon-m-document-text" class="w-4 h-4 text-red-500 shrink-0" />
                                        <a href="#" 
                                           wire:click.prevent="mountAction('viewHistoryPdf', { mediaId: {{ $media->id }}, title: '{{ addslashes($modalTitle) }}' })" 
                                           class="hover:text-primary-600 dark:hover:text-primary-400 hover:underline font-semibold truncate"
                                           title="Click to view PDF in modal">
                                            {{ $media->file_name }}
                                        </a>
                                    </div>
                                </td>
                                <td class="px-4 py-3 text-gray-600 dark:text-gray-300">
                                    {{ $dateStr }}
                                </td>
                                <td class="px-4 py-3 text-gray-600 dark:text-gray-300">
                                    {{ $byName }}
                                </td>
                                <td class="px-4 py-3 text-gray-500 dark:text-gray-400 text-[11px]">
                                    {{ $sizeStr }}
                                </td>
                                <td class="px-4 py-3 text-right">
                                    <div class="flex items-center justify-end gap-1.5">
                                        <button type="button"
                                                wire:click.prevent="mountAction('viewHistoryPdf', { mediaId: {{ $media->id }}, title: '{{ addslashes($modalTitle) }}' })"
                                                class="inline-flex items-center gap-1 px-2.5 py-1 rounded-md text-xs font-semibold {{ $isLatest ? 'bg-primary-600 text-white hover:bg-primary-500 shadow-sm' : 'bg-gray-100 dark:bg-white/10 text-gray-700 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-white/20' }} transition-colors">
                                            <x-filament::icon icon="heroicon-m-eye" class="w-3.5 h-3.5" />
                                            <span>Preview</span>
                                        </button>
                                        <a href="{{ $streamUrl }}" 
                                           target="_blank" 
                                           title="Open in new tab"
                                           class="p-1 rounded text-gray-500 hover:text-primary-600 dark:text-gray-400 dark:hover:text-primary-400 hover:bg-gray-100 dark:hover:bg-white/10 transition-colors">
                                            <x-filament::icon icon="heroicon-m-arrow-top-right-on-square" class="w-3.5 h-3.5" />
                                        </a>
                                        <a href="{{ $downloadUrl }}" 
                                           download
                                           title="Download file"
                                           class="p-1 rounded text-gray-500 hover:text-primary-600 dark:text-gray-400 dark:hover:text-primary-400 hover:bg-gray-100 dark:hover:bg-white/10 transition-colors">
                                            <x-filament::icon icon="heroicon-m-arrow-down-tray" class="w-3.5 h-3.5" />
                                        </a>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    @endif
</div>
