@php
    $mediaItems = collect();
    
    if ($record) {
        $generated = $record->getMedia('generated_quote_pdf');
        $legacy = $record->getMedia('quote_pdf');
        $mediaItems = $generated->concat($legacy)->sortByDesc('created_at')->values();
    }
    $mediaCount = $mediaItems->count();
@endphp

<div style="width: 100%;">
    @if($mediaItems->isEmpty())
        <div style="padding: 1.25rem; border-radius: 0.5rem; background: rgba(245, 158, 11, 0.08); border: 1px solid rgba(245, 158, 11, 0.25); font-size: 0.875rem; color: #92400e; display: flex; align-items: center; gap: 0.75rem;">
            <x-filament::icon icon="heroicon-o-document-text" style="width: 1.5rem; height: 1.5rem; color: #f59e0b; flex-shrink: 0;" />
            <div>
                <div style="font-weight: 700; font-size: 0.875rem;">Official Quotation PDF Not Generated Yet</div>
                <div style="font-size: 0.75rem; color: #b45309; margin-top: 0.125rem;">Click <strong>"Generate Quotation"</strong> above to compile the official customer-facing PDF with current line items and tax components.</div>
            </div>
        </div>
    @else
        <div style="border: 1px solid rgba(128, 128, 128, 0.2); border-radius: 0.5rem; overflow: hidden; background: inherit; box-shadow: 0 1px 2px rgba(0,0,0,0.05);">
            <div style="padding: 0.75rem 1rem; background: rgba(128, 128, 128, 0.04); border-bottom: 1px solid rgba(128, 128, 128, 0.15); display: flex; flex-wrap: wrap; align-items: center; justify-content: space-between; gap: 0.75rem;">
                <div style="display: flex; align-items: center; gap: 0.5rem;">
                    <x-filament::icon icon="heroicon-m-document-duplicate" style="width: 1rem; height: 1rem; color: #2563eb;" />
                    <span style="font-weight: 700; font-size: 0.75rem; text-transform: uppercase; letter-spacing: 0.05em;">Generated Quotation Documents</span>
                    <span style="display: inline-flex; align-items: center; padding: 0.125rem 0.5rem; border-radius: 9999px; font-size: 0.6875rem; font-weight: 600; background: rgba(37, 99, 235, 0.1); color: #2563eb; border: 1px solid rgba(37, 99, 235, 0.25);">
                        {{ $mediaCount }} {{ $mediaCount === 1 ? 'version' : 'versions' }}
                    </span>
                </div>
                <div style="font-size: 0.75rem; color: #6b7280;">
                    Quotation Grand Total: <strong style="font-weight: 700; font-size: 0.875rem; color: inherit;">₹{{ number_format($record->total_amount, 2) }}</strong>
                </div>
            </div>

            <div style="overflow-x: auto;">
                <table style="width: 100%; text-align: left; font-size: 0.75rem; border-collapse: collapse;">
                    <thead>
                        <tr style="background: rgba(128, 128, 128, 0.03); border-bottom: 1px solid rgba(128, 128, 128, 0.15); color: #6b7280; font-weight: 600; text-transform: uppercase; letter-spacing: 0.05em; font-size: 0.6875rem;">
                            <th style="padding: 0.75rem 1rem; width: 15%;">Version</th>
                            <th style="padding: 0.75rem 1rem; width: 30%;">File Name</th>
                            <th style="padding: 0.75rem 1rem; width: 20%;">Generated On</th>
                            <th style="padding: 0.75rem 1rem; width: 15%;">Generated By</th>
                            <th style="padding: 0.75rem 1rem; width: 8%;">Size</th>
                            <th style="padding: 0.75rem 1rem; width: 12%; text-align: right;">Actions</th>
                        </tr>
                    </thead>
                    <tbody style="border-top: 1px solid rgba(128, 128, 128, 0.1);">
                        @foreach ($mediaItems as $index => $media)
                            @php
                                $isLatest = ($index === 0);
                                $ver = $media->getCustomProperty('version') ?? ($mediaCount - $index);
                                $dateStr = $media->created_at ? $media->created_at->format('M d, Y h:i A') : '—';
                                $byName = $media->getCustomProperty('generated_by_name') ?? 'System';
                                $sizeStr = $media->human_readable_size ?? '—';
                                $modalTitle = "Official Client Quotation PDF (v{$ver}) - {$record->quote_number}";
                                $streamUrl = route('billing.quotation.pdf', ['quote' => $record->id, 'media_id' => $media->id]);
                                $downloadUrl = route('billing.quotation.pdf.download', ['quote' => $record->id, 'media_id' => $media->id]);
                            @endphp
                            <tr style="border-bottom: 1px solid rgba(128, 128, 128, 0.1); background-color: {{ $isLatest ? 'rgba(37, 99, 235, 0.04)' : 'transparent' }};">
                                <td style="padding: 0.75rem 1rem;">
                                    @if($isLatest)
                                        <span style="display: inline-flex; align-items: center; gap: 0.375rem; padding: 0.125rem 0.5rem; border-radius: 0.25rem; font-size: 0.6875rem; font-weight: 700; background: rgba(16, 185, 129, 0.15); color: #047857; border: 1px solid rgba(16, 185, 129, 0.3);">
                                            <span style="width: 0.375rem; height: 0.375rem; border-radius: 9999px; background-color: #10b981;"></span>
                                            v{{ $ver }} (Latest)
                                        </span>
                                    @else
                                        <span style="display: inline-flex; align-items: center; padding: 0.125rem 0.5rem; border-radius: 0.25rem; font-size: 0.6875rem; font-weight: 600; background: rgba(128, 128, 128, 0.1); color: #6b7280; border: 1px solid rgba(128, 128, 128, 0.15);">
                                            v{{ $ver }} (Archive)
                                        </span>
                                    @endif
                                </td>
                                <td style="padding: 0.75rem 1rem; font-weight: 500;">
                                    <div style="display: flex; align-items: center; gap: 0.5rem;">
                                        <x-filament::icon icon="heroicon-m-document-text" style="width: 1rem; height: 1rem; color: #ef4444; flex-shrink: 0;" />
                                        <a href="#" 
                                           wire:click.prevent="mountAction('viewHistoryPdf', { mediaId: {{ $media->id }}, title: '{{ addslashes($modalTitle) }}' })" 
                                           style="color: #2563eb; font-weight: 600; text-decoration: none; overflow: hidden; text-overflow: ellipsis; white-space: nowrap;"
                                           title="Click to view PDF in modal">
                                            {{ $media->file_name }}
                                        </a>
                                    </div>
                                </td>
                                <td style="padding: 0.75rem 1rem; color: #4b5563;">
                                    {{ $dateStr }}
                                </td>
                                <td style="padding: 0.75rem 1rem; color: #4b5563;">
                                    {{ $byName }}
                                </td>
                                <td style="padding: 0.75rem 1rem; color: #6b7280; font-size: 0.6875rem;">
                                    {{ $sizeStr }}
                                </td>
                                <td style="padding: 0.75rem 1rem; text-align: right;">
                                    <div style="display: flex; align-items: center; justify-content: flex-end; gap: 0.375rem;">
                                        <button type="button"
                                                wire:click.prevent="mountAction('viewHistoryPdf', { mediaId: {{ $media->id }}, title: '{{ addslashes($modalTitle) }}' })"
                                                style="display: inline-flex; align-items: center; gap: 0.25rem; padding: 0.25rem 0.625rem; border-radius: 0.375rem; font-size: 0.75rem; font-weight: 600; border: none; cursor: pointer; {{ $isLatest ? 'background-color: #2563eb; color: #ffffff;' : 'background-color: rgba(128, 128, 128, 0.1); color: #374151;' }}">
                                            <x-filament::icon icon="heroicon-m-eye" style="width: 0.875rem; height: 0.875rem;" />
                                            <span>Preview</span>
                                        </button>
                                        <a href="{{ $streamUrl }}" 
                                           target="_blank" 
                                           title="Open in new tab"
                                           style="padding: 0.25rem; border-radius: 0.25rem; color: #6b7280; text-decoration: none;">
                                            <x-filament::icon icon="heroicon-m-arrow-top-right-on-square" style="width: 0.875rem; height: 0.875rem;" />
                                        </a>
                                        <a href="{{ $downloadUrl }}" 
                                           download
                                           title="Download file"
                                           style="padding: 0.25rem; border-radius: 0.25rem; color: #6b7280; text-decoration: none;">
                                            <x-filament::icon icon="heroicon-m-arrow-down-tray" style="width: 0.875rem; height: 0.875rem;" />
                                        </a>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    @endif
</div>
